from typing_extensions import TypedDict


class GraphState(TypedDict):
    """
    Represents the state of the search agent workflow graph.

    This class defines the structure and types of data that flow through the graph nodes
    during workflow execution. It tracks the original question, transformed search query,
    web search results, and final generated response.

    Attributes:
        question (str): The original user question or search query
        generation (str): The final natural language response generated by the LLM
        search_query (str): The transformed/optimized version of the question for web search
        context (str): The raw results and context retrieved from web search
    """

    question: str
    generation: str
    search_query: str 
    context: str
